"""
Django settings for home_improvement project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs, unquote
from decouple import config

# Repository layout:
#
#   backend/   Django project + apps (Python only)
#   frontend/  templates, static assets, captured page sources
#
# BASE_DIR is the backend directory so it stays the anchor for app code.
# REPO_ROOT is the checkout root, and FRONTEND_DIR holds everything that is
# presented to a visitor.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent
FRONTEND_DIR = REPO_ROOT / 'frontend'


def _blank_to_default(name, default, cast):
    """Read an env var, treating an empty value as "not set".

    Deployment dashboards keep a key whose value field was left empty as an
    empty string rather than dropping it. `config(..., cast=int)` on such a
    value raises `ValueError: invalid literal for int() with base 10: ''` while
    the settings module is being imported, which fails the build with a
    traceback that names neither the variable nor the remedy.

    In practice a blank value means "not configured yet", so fall back to the
    default and let `scripts/preflight.py` report the real problem with a
    message that names it.

    The cast is applied to the default as well as to a present value, because
    decouple casts its default too. Skipping that returns a default of the
    wrong type: a blank CSRF_TRUSTED_ORIGINS would yield the bare string
    "https://example.com" instead of a list, and Django then validates each
    character of it as an origin.
    """
    raw = config(name, default="")
    if raw is None or not str(raw).strip():
        raw = default
    return cast(raw)


def _int_env(name, default, minimum=None):
    """Read an integer env var, tolerating a blank value.

    A present-but-unparseable value is a genuine typo and still raises, but as
    ImproperlyConfigured naming the variable and the bad value, instead of a
    bare ValueError from inside decouple naming neither.
    """
    raw = config(name, default="")
    if raw is None or not str(raw).strip():
        raw = default
    try:
        value = int(raw)
    except (TypeError, ValueError):
        raise ImproperlyConfigured(
            f"{name} must be a whole number, but is set to {raw!r}."
        ) from None
    if minimum is not None and value < minimum:
        raise ImproperlyConfigured(
            f"{name} must be >= {minimum}, but is set to {raw!r}."
        )
    return value


def _bool_env(name, default):
    """Read a boolean env var, treating a blank value as "not set".

    decouple's `cast=bool` calls bool() on the raw string, so a variable that
    was added to the deployment dashboard with an empty value field becomes
    False rather than falling back to the default. For SESSION_COOKIE_SECURE
    and CSRF_COOKIE_SECURE that silently *downgrades* security, which is worse
    than the crash it avoids.
    """
    return _blank_to_default(
        name, default,
        lambda v: str(v).strip().lower() in ('1', 'true', 'yes', 'on'),
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/topics/settings/

from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _bool_env('DEBUG', False)

# Hostnames this site answers to.
#
# No domain is required to deploy. Render assigns a hostname nobody can
# predict ahead of time, so a first deploy works on the *.onrender.com
# subdomain alone and a real domain can be attached later.
_ALLOWED_HOSTS_DEFAULT = 'localhost,127.0.0.1,[::1]'
ALLOWED_HOSTS = _blank_to_default(
    'ALLOWED_HOSTS',
    _ALLOWED_HOSTS_DEFAULT,
    lambda v: [h.strip() for h in str(v).split(',') if h.strip()],
)
if not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS resolved to an empty list. Set it to the hostname the "
        "site is served from, e.g. ALLOWED_HOSTS=example.com,www.example.com — "
        "without it every request returns 400."
    )

# Django reads a leading dot as "this domain and all subdomains", which covers
# every hostname Render generates. Kept platform-scoped rather than a
# blanket wildcard because ALLOWED_HOSTS is also the host-header trust
# boundary; a custom domain still has to be listed explicitly.
if os.environ.get('RENDER'):
    if '.onrender.com' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.onrender.com')

# Canonical site origin, used for <link rel="canonical">, Open Graph URLs and
# the sitemap. Left empty by default so the templates fall back to the host of
# the incoming request (see main.context_processors.site): that keeps canonical
# and og: tags pointing at the address visitors actually used, instead of at a
# hostname guessed at build time or hardcoded to a domain the operator may not
# even own.
SITE_URL = _blank_to_default('SITE_URL', '', lambda v: v).rstrip('/')


# Application definition

INSTALLED_APPS = [
    # Replaces django.contrib.admin: same app, but admin.site resolves to
    # main.admin_site.StudioAdminSite so /admin/ opens on the dashboard.
    'main.admin_config.StudioAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'main',
    'crm',
    'content',
]

INSTALLED_APPS.extend(EXTERNAL_APPS)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================
# HTTPS / SECURITY SETTINGS
# =============================

# Force HTTPS. Enabled in production only — with it on in local dev, Django
# 301-redirects every request to https:// and the dev server has no TLS cert,
# producing an infinite redirect loop.
SECURE_SSL_REDIRECT = _bool_env('SECURE_SSL_REDIRECT', not DEBUG)

# The Edge/load balancer terminates TLS upstream, so Django sees plain HTTP
# unless it is told to trust the forwarding header. The host allowlist stays
# authoritative: an unrecognised Host still gets a 400, this only affects
# scheme/cookie handling for hosts that are already allowed.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Origins permitted to submit CSRF-protected POSTs from a *different* origin
# than the one serving the request -- e.g. the bare apex while the www host is
# serving, or a custom domain alongside the platform subdomain.
#
# Left empty by default on purpose. Django already accepts a POST whose Origin
# matches the host serving it, so a single-hostname deployment needs nothing
# here. That matters for a first deploy, where the hostname is not known until
# after the build: a hardcoded list cannot be right, and a wrong one makes
# every form POST 403 while GETs keep working.
def _origin(value):
    """Normalise an origin to scheme+host, without doubling the scheme.

    SITE_URL already carries a scheme ("https://example.com"), so naively
    prefixing one produces "https://https://example.com", which matches no real
    Origin header and silently 403s every form POST.
    """
    value = str(value).strip().rstrip('/')
    if not value:
        return ''
    if '://' not in value:
        value = 'https://' + value
    return value


# The default is a plain string, not a pre-built list. The cast below splits a
# string on commas, so handing it a list default would stringify the list and
# then split the repr -- yielding a single bogus origin like
# "['https://example.com']" that matches no Origin header.
_CSRF_RAW = _blank_to_default('CSRF_TRUSTED_ORIGINS', '', lambda v: v)
CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in (_origin(part) for part in str(_CSRF_RAW).split(','))
    if origin
]
if not CSRF_TRUSTED_ORIGINS and SITE_URL:
    CSRF_TRUSTED_ORIGINS = [_origin(SITE_URL)]

# Secure cookies. A "Secure" cookie is withheld by the browser over plain HTTP,
# so leaving these on would make every form POST fail with 403 during local dev
# against the runserver. Off in DEBUG, on in production.
SESSION_COOKIE_SECURE = _bool_env('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _bool_env('CSRF_COOKIE_SECURE', not DEBUG)

# Optional: SameSite policy for extra security
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HSTS (HTTP Strict Transport Security)
# HSTS is host-scoped and preload is submitted per registrable domain, so
# these are configurable rather than hardcoded: a deployment served from a
# shared platform hostname (e.g. *.onrender.com) must not inherit a one-year
# include-subdomains policy or be submitted to the preload list, because that
# would affect every other site sharing that platform's parent domain.
SECURE_HSTS_SECONDS = _int_env('SECURE_HSTS_SECONDS', 31536000, minimum=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _bool_env('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _bool_env('SECURE_HSTS_PRELOAD', False)

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Frontend content is stored in the database and compiled by the template
# engine, so stored sections can use {% static %}, {% url %} and
# {% csrf_token %}. That makes content-editing accounts as powerful as template
# authors, so section/page change permissions should be restricted to trusted
# staff. Set False to treat stored section HTML as literal text instead.
CONTENT_ALLOW_TEMPLATES = _bool_env('CONTENT_ALLOW_TEMPLATES', True)


MIDDLEWARE = [
    # First, so every later middleware and the view can see the request
    # on the audit thread-local. It must also be outside
    # WhiteNoiseMiddleware, which short-circuits static requests before
    # they reach anything else.
    'crm.middleware.AuditContextMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Added first so it can respond to static requests before any database or
    # session access, keeping cached assets off the request path entirely.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Cache lifetime for WhiteNoise-served assets. Deliberately not a year: the
# non-manifest storage backend above does not fingerprint filenames, so a long
# TTL would make clients hold a stale CSS/JS file after a deploy. Raise it only
# if asset names are made content-addressed.
WHITENOISE_MAX_AGE = _int_env('WHITENOISE_MAX_AGE', 3600, minimum=0)

ROOT_URLCONF = 'home_improvement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Project-level overrides, e.g. admin/login.html.
            os.path.join(FRONTEND_DIR, 'templates'),
            # The runtime shell: base.html plus the nav/foot/post partials.
            # These are referenced unprefixed ("base.html",
            # "partials/_nav_1.html") throughout the stored page markup, so
            # they must be on DIRS now that they no longer live inside an
            # app's templates/ directory.
            os.path.join(FRONTEND_DIR, 'templates_main'),
            # The page templates captured from the live site. They are import
            # input and the legacy fallback used if a Page row is missing, not
            # the runtime templates. Listed here so {% extends 'main/x.html' %}
            # still resolves for that fallback.
            os.path.join(FRONTEND_DIR, 'source_templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site',
                'main.context_processors.site_settings',
                'main.context_processors.navigation',
                'main.context_processors.services',
            ],
            # Stored page content is compiled on its own by content.render, so
            # it cannot rely on a {% load static %} in a parent template.
            # Registering the libraries as builtins makes {% static %} and
            # {% csrf_token %} available inside database-backed sections.
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_improvement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Local development stays on sqlite so `manage.py` works with no setup.
# Deployment sets DATABASE_URL, because a container filesystems are ephemeral:
# a db.sqlite3 written inside a function invocation is thrown away when that
# instance is recycled, so it can never hold real content or leads.
DATABASE_URL = config('DATABASE_URL', default='')

# Substrings that mean the value is a copy of the documentation rather than a
# real credential. A connection string is easy to write from a template and
# hard to eyeball, and the failure is maximally unhelpful: Postgres accepts the
# host, resolves DNS, and then answers
#
#   password authentication failed for user 'USER'
#
# which reads like a wrong password rather than an unsubstituted placeholder,
# and it does so once per connection attempt across every IP in the pooler
# record, so `migrate`, `capture_content` and `createsuperuser` each produce a
# full traceback and bury the one line that matters. Caught here instead, at
# import, so it is one message on the first command.
PLACEHOLDER_MARKERS = (
    'USER', 'PASSWORD', 'username', 'password', 'your-', 'your_', 'youruser',
    'ep-xxx', 'CHANGEME', 'changeme', 'TODO', 'REPLACE_ME', '<', 'xxx',
)


def _reject_placeholder_credentials(url):
    """Fail loudly if DATABASE_URL still contains template text."""
    parsed = urlparse(url)
    # Only the userinfo is inspected. The host legitimately contains "xxx" in
    # some sandbox hostnames, and the query string carries no credentials.
    userinfo = parsed.netloc.rsplit('@', 1)[0]
    hits = [m for m in PLACEHOLDER_MARKERS if m in userinfo]
    if hits:
        raise ValueError(
            "DATABASE_URL contains placeholder text "
            f"({', '.join(repr(h) for h in hits)}) in its username or password. "
            "This looks like a copy of the example in the deploy guide, not a "
            "real credential. Copy the connection string from the Neon "
            "console (or `npx vercel env pull`) and export it again. Replace "
            "USER, PASSWORD and the ep-xxx host with your actual values."
        )



def _postgres_from_url(url):
    """Build a postgres DATABASES entry from a connection URI.

    The query string is split with urllib only, deliberately without importing
    psycopg. Settings are imported by `collectstatic` during the build,
    which never opens a database connection, yet importing a C extension purely
    to split a query string made the whole build depend on a libpq wheel that
    the build image could not load ("ImportError: no pq wrapper available").

    Every parameter is forwarded to libpq unchanged. An earlier hand-rolled
    allowlist silently dropped anything it did not recognise --
    `channel_binding=require`, which is exactly the kind of security setting
    that must not disappear without a word. Unknown options are still caught,
    just not at import time: libpq rejects them when connecting, and
    scripts/preflight.py reports them by name before a deploy.
    """
    parsed = urlparse(url)
    _reject_placeholder_credentials(url)
    if parsed.scheme not in ('postgres', 'postgresql', 'psql', 'pgsql'):
        raise ValueError(
            f"Unsupported DATABASE_URL scheme {parsed.scheme!r}; expected "
            "postgres:// or postgresql://"
        )

    query = parse_qs(parsed.query, keep_blank_values=True)
    # conn_max_age is a Django-level pooling knob, not a libpq option, so it
    # must be removed before the rest are handed to libpq. It is the one
    # parameter this project accepts beyond the libpq set.
    conn_max_age = int(query.get('conn_max_age', ['60'])[0])
    libpq_query = {k: v for k, v in query.items() if k != 'conn_max_age'}

    # Mirrors psycopg.conninfo.conninfo_to_dict, including percent-decoding of
    # the userinfo component, and keeps blank values so `?sslmode=` stays
    # visible instead of silently becoming absent.
    params = {}
    if parsed.username is not None:
        params['user'] = unquote(parsed.username)
    if parsed.password is not None:
        params['password'] = unquote(parsed.password)
    params['host'] = parsed.hostname or ''
    try:
        params['port'] = str(parsed.port) if parsed.port else ''
    except ValueError:
        raise ValueError(
            f"DATABASE_URL has an invalid port in {parsed.netloc!r}"
        ) from None
    dbname = unquote(parsed.path.lstrip('/'))
    if dbname:
        params['dbname'] = dbname
    for key, values in libpq_query.items():
        # libpq honours the last occurrence of a repeated keyword.
        params[key] = values[-1]

    options = {
        key: value
        for key, value in params.items()
        if key not in ('dbname', 'user', 'password', 'host', 'port')
    }
    # Bound how long a connection attempt may block. A serverless request has
    # a hard wall-clock limit and cannot afford to wait on a dead host.
    options.setdefault('connect_timeout', 10)

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': params.get('dbname', ''),
        'USER': params.get('user', ''),
        'PASSWORD': params.get('password', ''),
        'HOST': params.get('host', ''),
        'PORT': str(params.get('port', '') or ''),
        'OPTIONS': options,
        'CONN_MAX_AGE': conn_max_age,
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }


if DATABASE_URL:
    DATABASES = {'default': _postgres_from_url(DATABASE_URL)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Leading slash is required: a relative value breaks {% static %} on nested
# URLs (e.g. /about/ would resolve 'static/x.css' to /about/static/x.css).
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS = [
    os.path.join(FRONTEND_DIR, 'static')
]
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# Static files are served by WhiteNoise from inside the app bundle, because a
# container deployment has no persistent filesystem and no separate web
# server to hand static assets off to. Without it, every CSS/image request 404s.
#
# The non-manifest storage backend is deliberate. A manifest backend rewrites
# {% static %} to fingerprinted names, but this site's HTML is largely mirrored
# from the live site and hardcodes asset paths inside inline <style> blocks and
# data attributes that no template tag rewrites. Switching to the manifest
# backend would leave those pointing at unhashed paths that no longer exist,
# silently breaking styling sitewide. The compressed variant still gzips and
# caches aggressively without renaming anything.
if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

# Pin test discovery to backend/ so `manage.py test` finds the apps no matter
# which directory it is invoked from. See home_improvement/runner.py.
TEST_RUNNER = 'home_improvement.runner.BackendDiscoverRunner'


# Content cache.
#
# The database backend, not the default local-memory one, and that distinction
# decides whether the site is correct. Gunicorn runs two workers
# (see render.yaml); local-memory cache is per-process, so an editor who saves
# a menu in the worker handling the POST invalidates only that worker's copy
# and the other one keeps serving the old navigation until the next deploy. The
# django_cache table is created by a migration, so it exists on every deploy and
# in the test database without a manual `createcachetable` step.
#
# Nothing here expires on a timer. The cached values (site settings, navigation
# tree, service list) are invalidated by the admin write paths in
# content.cache, and a stale entry that is never invalidated is a bug worth
# seeing rather than one worth papering over with a short TTL.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': _blank_to_default('CACHE_TABLE', 'django_cache',
                                      lambda v: v),
        'TIMEOUT': _int_env('CACHE_TIMEOUT', 0, minimum=0),
    }
}

#django message framework
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.SUCCESS: "success",
    messages.ERROR: "danger",
    50: "critical",
}

# Email defaults to the console backend so that a deployment which has not
# finished configuring SMTP still *builds and serves pages*. Nine mandatory
# variables here previously meant the build could not succeed at all until
# working SMTP credentials existed, which blocks deploying the site itself over
# a missing notification channel.
#
# This is deliberately not silent: scripts/preflight.py fails on the console
# backend, on an empty ADMIN_EMAIL, and on EMAIL_USE_SSL/EMAIL_USE_TLS both
# being set, so an unconfigured mail setup blocks a release rather than
# quietly dropping lead notifications.
EMAIL_BACKEND = _blank_to_default(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
    lambda v: v,
)
EMAIL_HOST = _blank_to_default('EMAIL_HOST', '', lambda v: v)
EMAIL_PORT = _int_env('EMAIL_PORT', 587, minimum=1)
EMAIL_USE_TLS = _bool_env('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _bool_env('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = _blank_to_default('EMAIL_HOST_USER', '', lambda v: v)
EMAIL_HOST_PASSWORD = _blank_to_default('EMAIL_HOST_PASSWORD', '', lambda v: v)

# Bound how long a send may block. A containerised request has a hard wall-clock
# limit, and a hung SMTP connection would otherwise hold the invocation open
# until it is killed. Failures are already caught in crm.services, so an
# early timeout degrades to "no notification" instead of a dead request.
EMAIL_TIMEOUT = _int_env('EMAIL_TIMEOUT', 10, minimum=1)

# --- Email addresses ---
DEFAULT_FROM_EMAIL = _blank_to_default('DEFAULT_FROM_EMAIL', 'webmaster@localhost', lambda v: v)
# Comma-separated, blanks dropped: a trailing comma must not become a recipient.
ADMIN_EMAIL = [
    addr.strip()
    for addr in _blank_to_default('ADMIN_EMAIL', '', lambda v: v).split(',')
    if addr.strip()
]

# Refuse to serve with DEBUG on a real Render service. Debug mode renders
# detailed tracebacks containing settings and environment values, and it
# changes how static files are served, so a single mis-set variable in
# deployment would expose the configuration. Render sets RENDER=1 on every
# deployed service and leaves it unset in local development.
if DEBUG and os.environ.get('RENDER'):
    raise RuntimeError(
        'DEBUG is True but RENDER is set. Debug mode must never be enabled '
        'on a deployed service; it renders settings and environment values in '
        'error pages. Unset DEBUG and redeploy.'
    )