# Generated by Django 5.2.13 on 2026-09-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='footer_variant',
            field=models.CharField(blank=True, help_text='Footer partial, e.g. partials/_foot_1.html', max_length=60),
        ),
        migrations.AlterField(
            model_name='page',
            name='nav_variant',
            field=models.CharField(blank=True, help_text='Navbar partial, e.g. partials/_nav_1.html', max_length=60),
        ),
        migrations.AlterField(
            model_name='page',
            name='post_variant',
            field=models.CharField(blank=True, help_text='Post-footer script partial, e.g. partials/_post_1.html', max_length=60),
        ),
    ]
