# Generated by Django 5.2.13 on 2026-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_page_footer_variant_alter_page_nav_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m')),
                ('title', models.CharField(blank=True, help_text='Shown in the library. Falls back to the filename.', max_length=160)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the image for screen readers and when it fails to load. Used by pickers when they build an img tag.', max_length=200)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished images stay in the library but are hidden from pickers. Untick to retire an image without breaking live pages that already reference it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media item',
                'verbose_name_plural': 'Media library',
                'ordering': ('-created_at',),
            },
        ),
    ]
