# Generated by Django 5.2.13 on 2026-09-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(blank=True, help_text='Repo path (img/photo.jpg), an uploaded /media/... path, or a full URL. Use the picker to choose from the library.', max_length=300)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the image for screen readers. Required for accessibility even though the captured copy left four images with none.', max_length=300)),
                ('caption', models.TextField(blank=True, help_text='Optional. Rendered as a <figcaption>, which wraps the image in a <figure>.')),
                ('css_class', models.CharField(blank=True, editable=False, max_length=200)),
                ('dom_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('inline_style', models.CharField(blank=True, editable=False, max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.section')),
            ],
            options={
                'verbose_name': 'section image',
                'verbose_name_plural': 'section images',
                'ordering': ['section', 'position', 'pk'],
            },
        ),
    ]
