# Generated by Django 5.2.13 on 2026-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content_body',
            field=models.TextField(blank=True, help_text='What this section says. Written in the editor on the form -- no HTML needed. Leave it empty to keep the copy that was captured from the live site.'),
        ),
    ]
