# Generated by Django 5.2.13 on 2026-09-30 15:04

from django.db import migrations, models


def reconcile_statuses(apps, schema_editor):
    """Give every existing page a status that matches its visibility flag.

    The new `status` column defaults to "published" for rows that had
    `is_published=False`, which would have left the workflow saying a page is
    live when it is not.
    """
    Page = apps.get_model("content", "Page")
    Page.objects.filter(is_published=False).exclude(status="draft").update(status="draft")


def revert_statuses(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_page_published_at_page_published_by_page_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='sections_json',
            field=models.TextField(blank=True, help_text="The page's sections at snapshot time, as JSON."),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When a Scheduled page goes live. Left empty, a scheduled page stays offline.', null=True),
        ),
        migrations.RunPython(reconcile_statuses, revert_statuses),
    ]
