# Generated by Django 5.2.13 on 2026-09-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentrevision_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text="The content= value from Google's verification tag.", max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_title_suffix',
            field=models.CharField(blank=True, help_text="Appended to page titles after a pipe, e.g. 'Home Renovation & Remodeling'. Leave blank to use each page's title on its own.", max_length=120),
        ),
    ]
