# Generated by Django 5.2.13 on 2026-09-29 06:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], db_index=True, max_length=10)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['model', 'object_id', '-created_at'], name='crm_auditlo_model_eb4ba9_idx')],
            },
        ),
    ]
