# Generated by Django 5.2.13 on 2026-09-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('territory', models.CharField(blank=True, help_text='City or ZIP this member covers, matched against Lead.city_or_zip. Blank covers everywhere.', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Untick to stop assigning new leads. Existing ones are kept.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('assignment_count', models.PositiveIntegerField(default=0, help_text='Running total of leads assigned. The round-robin cursor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, help_text='Service this member covers. Blank covers every service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='crm.service')),
                ('user', models.ForeignKey(blank=True, help_text='The staff account that owns the lead. A member without one cannot be assigned leads and is skipped by round-robin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
