# Generated by Django 5.2.13 on 2026-09-30 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
