# Generated by Django 5.2.13 on 2026-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_service_created_at_service_cta_label_service_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page_body',
            field=models.TextField(blank=True, help_text="The service page's body. Left empty, the page is built from the name, description and image above."),
        ),
    ]
