"""
Django settings for home_improvement project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs, unquote
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='homeimp.quantumcoresoftware.com,www.homeimp.quantumcoresoftware.com',
    cast=lambda v: [h.strip() for h in str(v).split(',') if h.strip()],
)

# Canonical site origin. Used for <link rel="canonical">, Open Graph URLs and
# the sitemap. Falls back to the primary ALLOWED_HOSTS entry when unset.
SITE_URL = config('SITE_URL', default=f"https://{ALLOWED_HOSTS[0]}").rstrip('/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'main',
    'crm',
    'content',
]

INSTALLED_APPS.extend(EXTERNAL_APPS)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================
# HTTPS / SECURITY SETTINGS
# =============================

# Force HTTPS. Enabled in production only — with it on in local dev, Django
# 301-redirects every request to https:// and the dev server has no TLS cert,
# producing an infinite redirect loop.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)

# The Edge/load balancer terminates TLS upstream, so Django sees plain HTTP
# unless it is told to trust the forwarding header. The host allowlist stays
# authoritative: an unrecognised Host still gets a 400, this only affects
# scheme/cookie handling for hosts that are already allowed.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Origins permitted to submit CSRF-protected POSTs. Required on any new
# deployment hostname: without the production origin listed here, every
# admin form POST (and the lead form) fails with 403 "CSRF verification
# failed", while GETs keep working — so the site looks healthy and only
# writing breaks.
def _origin(value):
    """Normalise an origin to scheme+host, without doubling the scheme.

    SITE_URL already carries a scheme ("https://rlecd.com"), so naively
    prefixing one produces "https://https://rlecd.com", which matches no real
    Origin header and silently 403s every form POST.
    """
    value = str(value).strip().rstrip('/')
    if not value:
        return ''
    if '://' not in value:
        value = 'https://' + value
    return value


CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default=_origin(SITE_URL),
    cast=lambda v: [o for o in (_origin(o) for o in str(v).split(',')) if o],
)

# Secure cookies. A "Secure" cookie is withheld by the browser over plain HTTP,
# so leaving these on would make every form POST fail with 403 during local dev
# against the runserver. Off in DEBUG, on in production.
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)

# Optional: SameSite policy for extra security
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HSTS (HTTP Strict Transport Security)
# HSTS is host-scoped and preload is submitted per registrable domain, so
# these are configurable rather than hardcoded: a deployment served from a
# shared platform hostname (e.g. *.vercel.app) must not inherit a one-year
# include-subdomains policy or be submitted to the preload list, because that
# would affect every other site sharing that platform's parent domain.
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Frontend content is stored in the database and compiled by the template
# engine, so stored sections can use {% static %}, {% url %} and
# {% csrf_token %}. That makes content-editing accounts as powerful as template
# authors, so section/page change permissions should be restricted to trusted
# staff. Set False to treat stored section HTML as literal text instead.
CONTENT_ALLOW_TEMPLATES = config('CONTENT_ALLOW_TEMPLATES', default=True, cast=bool)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Added first so it can respond to static requests before any database or
    # session access, keeping cached assets off the request path entirely.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Cache lifetime for WhiteNoise-served assets. Deliberately not a year: the
# non-manifest storage backend above does not fingerprint filenames, so a long
# TTL would make clients hold a stale CSS/JS file after a deploy. Raise it only
# if asset names are made content-addressed.
WHITENOISE_MAX_AGE = config('WHITENOISE_MAX_AGE', default=3600, cast=int)

ROOT_URLCONF = 'home_improvement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            # The page templates captured from the live site. They are import
            # input and the legacy fallback used if a Page row is missing, not
            # the runtime templates. Listed here so {% extends 'main/x.html' %}
            # still resolves for that fallback.
            os.path.join(BASE_DIR, 'content', 'source_templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site',
            ],
            # Stored page content is compiled on its own by content.render, so
            # it cannot rely on a {% load static %} in a parent template.
            # Registering the libraries as builtins makes {% static %} and
            # {% csrf_token %} available inside database-backed sections.
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_improvement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Local development stays on sqlite so `manage.py` works with no setup.
# Deployment sets DATABASE_URL, because serverless filesystems are ephemeral:
# a db.sqlite3 written inside a function invocation is thrown away when that
# instance is recycled, so it can never hold real content or leads.
DATABASE_URL = config('DATABASE_URL', default='')


def _postgres_from_url(url):
    """Build a postgres DATABASES entry from a connection URI.

    Hand-parsed rather than pulling in dj-database-url to keep the deploy
    dependency list short; this is a fraction of the line count of the package
    and the whole surface actually used here.
    """
    parsed = urlparse(url)
    if parsed.scheme not in ('postgres', 'postgresql', 'psql', 'pgsql'):
        raise ValueError(
            f"Unsupported DATABASE_URL scheme {parsed.scheme!r}; expected "
            "postgres:// or postgresql://"
        )
    query = parse_qs(parsed.query)
    # Managed Postgres providers (Neon, Supabase, Heroku, Railway) append
    # sslmode=require and friends as query params. libpq has dedicated
    # options for some of these but no Django setting, so they belong in
    # OPTIONS. conn_max_age is deliberately NOT put here: it is a Django-level
    # pooling setting, and libpq rejects it as an unknown connection option.
    options = {}
    if 'sslmode' in query:
        options['sslmode'] = query['sslmode'][0]
    if 'connect_timeout' in query:
        options['connect_timeout'] = int(query['connect_timeout'][0])
    else:
        # Serverless invocations are short-lived and often bursty. Holding a
        # pooled connection open for the function's lifetime keeps Postgres
        # from being saturated by cold-start traffic, so 60s rather than 0.
        options['connect_timeout'] = 10
    conn_max_age = int(query.get('conn_max_age', ['60'])[0])
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
        'OPTIONS': options,
        'CONN_MAX_AGE': conn_max_age,
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }


if DATABASE_URL:
    DATABASES = {'default': _postgres_from_url(DATABASE_URL)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Leading slash is required: a relative value breaks {% static %} on nested
# URLs (e.g. /about/ would resolve 'static/x.css' to /about/static/x.css).
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# Static files are served by WhiteNoise from inside the app bundle, because a
# serverless deployment has no persistent filesystem and no separate web
# server to hand static assets off to. Without it, every CSS/image request 404s.
#
# The non-manifest storage backend is deliberate. A manifest backend rewrites
# {% static %} to fingerprinted names, but this site's HTML is largely mirrored
# from the live site and hardcodes asset paths inside inline <style> blocks and
# data attributes that no template tag rewrites. Switching to the manifest
# backend would leave those pointing at unhashed paths that no longer exist,
# silently breaking styling sitewide. The compressed variant still gzips and
# caches aggressively without renaming anything.
if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

#django message framework
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.SUCCESS: "success",
    messages.ERROR: "danger",
    50: "critical",
}

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# Bound how long a send may block. A serverless request has a hard wall-clock
# limit, and a hung SMTP connection would otherwise hold the invocation open
# until it is killed. Failures are already caught in crm.services, so an
# early timeout degrades to "no notification" instead of a dead request.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# --- Email addresses ---
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
ADMIN_EMAIL = config('ADMIN_EMAIL').split(',')

# Refuse to serve with DEBUG on in a real Vercel environment. Debug mode
# renders detailed tracebacks containing settings and environment values, and
# it changes how static files are served, so a single mis-set variable in
# deployment would expose the configuration. VERCEL_ENV is 'development' for
# `vercel dev` and 'preview'/'production' for deployed builds.
VERCEL_ENV = os.environ.get('VERCEL_ENV', '')

if DEBUG and VERCEL_ENV in ('preview', 'production'):
    raise RuntimeError(
        f'DEBUG is True but VERCEL_ENV={VERCEL_ENV!r}. Debug mode must never '
        'be enabled on a deployed build; it renders settings and environment '
        'values in error pages. Unset DEBUG and redeploy.'
    )