# Generated by Django 5.2.13 on 2026-09-28 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(help_text='Internal page name.', max_length=200)),
                ('path', models.CharField(help_text="URL path, e.g. '/' or '/about/'. Must match urls.py.", max_length=200, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('head_html', models.TextField(blank=True, help_text='Contents of the head_meta block, exactly as shipped.')),
                ('main_attrs', models.CharField(blank=True, help_text='Attributes the live page puts on <main>, e.g. class="contact-page".', max_length=200)),
                ('nav_variant', models.CharField(blank=True, help_text='Navbar partial, e.g. _nav_1.html', max_length=60)),
                ('footer_variant', models.CharField(blank=True, help_text='Footer partial, e.g. _foot_1.html', max_length=60)),
                ('post_variant', models.CharField(blank=True, help_text='Post-footer script partial, e.g. _post_1.html', max_length=60)),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=400)),
                ('og_image', models.CharField(blank=True, max_length=300)),
                ('noindex', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('group', models.CharField(blank=True, db_index=True, help_text="Optional grouping, e.g. 'Baltimore County'.", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('blurb', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='REAL LIFE EXPERIENCE LLC', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('service_area_summary', models.CharField(blank=True, max_length=240)),
                ('years_in_business', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5. Used for AggregateRating schema.')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='crm.service')),
                ('page', models.ForeignKey(blank=True, help_text='Leave blank for site-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.page')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, help_text='Static path or URL, e.g. /static/img/kitchen1.jpg.', max_length=300)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=80)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.service')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.servicearea')),
            ],
            options={
                'ordering': ['-completed_on', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier, used in templates and for reordering.', max_length=120)),
                ('label', models.CharField(blank=True, help_text='Shown in the CRM list. Auto-derived from the first heading.', max_length=200)),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('features', 'Feature grid'), ('gallery', 'Gallery'), ('stats', 'Stats / numbers'), ('text', 'Text block'), ('cta', 'Call to action'), ('form', 'Lead form'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('areas', 'Service areas'), ('style', 'Style block'), ('html', 'Raw HTML')], default='html', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('content_html', models.TextField()),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
                ('is_locked', models.BooleanField(default=False, help_text='Structural chunks (page <style>, nested <main>). Keep these.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['page', 'position'],
                'indexes': [models.Index(fields=['page', 'position'], name='content_sec_page_id_9d13e2_idx')],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
